on:
  push:
    branches:
      - 'main'
    paths:
      - '**/*'
      - '!docs'
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: Release
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: |
            mshafer1/headless_chrome
      - name: Build Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          push: false
          tags: dev/chrome:latest
      - name: Get chrome version
        id: chrome_version
        run: |
          docker run --rm dev/chrome "google-chrome --version | sed -r 's/^.+Chrome //g' | tr -d '\n' | tr -d ' ' | cut -d'.' -f1-3"
        
